---
# k3s install and configuration only
#
# Usage:
#   cd ansible && ansible-playbook playbooks/k3s.yml -i inventory/dev.yml

- name: Install and configure k3s
  hosts: k3s
  become: true
  roles:
    - role: ../roles/k3s
