apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vafi.fullname" . }}-sessions
  labels:
    {{- include "vafi.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.sessions.storageClassName }}
  storageClassName: {{ .Values.sessions.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sessions.storage }}
