apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vafi-agents

resources:
  - sessions-pvc.yaml
  - secrets.yaml
  - executor-pool.yaml

commonLabels:
  app.kubernetes.io/part-of: vafi
  app.kubernetes.io/version: v0.1.0